repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: check-yaml
            args: [--unsafe]
          - id: debug-statements
          - id: double-quote-string-fixer
          - id: requirements-txt-fixer
          - id: check-added-large-files
            args: ["--maxkb=512"]
    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.15.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.2.0
      hooks:
          - id: add-trailing-comma
    - repo: https://github.com/asottile/pyupgrade # upgrades old style python code to newver version
      rev: v3.15.0
      hooks:
          - id: pyupgrade
            args: [--py39-plus]
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.3.1
      hooks:
          - id: autoflake
            args: [--remove-all-unused-imports, --in-place]
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.0.4
      hooks:
          - id: autopep8
            args: ["--max-line-length=120", "--in-place", "--aggressive"]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.18.2
      hooks:
          - id: mypy
            args: [
                    "--ignore-missing-imports",
                    "--allow-untyped-decorators", # remove if not needed
                    "--strict",
                    "--install-types",
                    "--non-interactive",
                ]
            # additional_dependencies:
            # - not_found_modules==23.1.0
    - repo: https://github.com/PyCQA/pylint
      rev: v3.3.0
      hooks:
          - id: pylint
            args: [
                    "--disable=C0114", # missing-module-docstring
                    "--disable=C0116", # missing-function-docstring
                ]

    # - repo: https://github.com/psf/black
    #   rev: 25.1.0
    #   hooks:
    #       - id: black
    #         language_version: python3.10
    # - repo: https://github.com/pre-commit/mirrors-prettier
    #   rev: v3.0.0
    #   hooks:
    #     - id: prettier
    #       args: ["--write"]
